# Data paths and options when using EleutherAI cluster
{
  # you may include multiple distinct datasets if desired

  # if using multiple datasets, provide weights for them to be sampled with
  # "train-data-weights": [1., 2.],
  # "test-data-weights": [2., 1.],
  # "valid-data-weights": [0.5, 0.4],


  # If you would like the code to create val and test datasets from your training set use the following instead
  # "split" determines the relative size of train, val, and test

  # "split" 995,4,1
  # "data_path": "/mnt/ssd-1/data/enwik8/enwik8_text_document",

  "launcher": "pdsh",
  "gradient_accumulation_steps": 16,
}
