ARG FROM_IMAGE_NAME=nvidia/cuda:12.9.0-devel-ubuntu22.04
FROM ${FROM_IMAGE_NAME}

# Install dependencies
RUN apt-get update \
 && apt-get install -y git 

WORKDIR /workspace
RUN git clone https://github.com/NVIDIA/nccl-tests.git

WORKDIR /workspace/nccl-tests
RUN make 

 
